### PR TITLE
Some fixes

### PR DESCRIPTION
**Pull request by ialbors**
A couple of fixes to problems I had with sconsify.

They're probably wrong but fixed the thing. Could you check them out?

### CODE REVIEW

**Comment by fabiofalci** [comment]
Hi @ialbors 

The first fix looks good.
The second one I'll need some time to test it as I don't quite remember that part now.

I'd happily merge the first one if you separate in a second pull request.

Thanks for the fixes!

**Comment by ialbors** [comment]
Yeah, sure!

I'm on it.

**Comment by unk1nd** [comment]
will the search fix be implemented? having problems with it in #22

**Comment by fabiofalci** [comment]
Yes, it'll be fixed. I was hoping to push to next 0.3.0 version however maybe we should release a fix 0.2.1 just with this fix.

**Comment by fabiofalci** [comment]
Fixed here: https://github.com/fabiofalci/sconsify/commit/87c605f8296c5da893fd6f8c8dfc8db35440f4e4#commitcomment-15506828

**Pull request closed without merging**
