### PR TITLE
Time duration feature

### PR DESCRIPTION
**Pull request by brownzach125**
Sorry it's taken so long. I got busy and struggled a little with go channels. 

Let me know what you think, I know it's little rough.

### CODE REVIEW

**Comment by fabiofalci** [comment]
No problem and don't worry about time.

I haven't looked the code, I've just merged and tested for some time. It seems to be working well.

The only thing, can you not divide the status bar 50/50? I was thinking in pushing the time to the right as much as we can so it doesn't take much space of the track name. Unless you are thinking in add a progress bar.

Anyhow, this progress bar can be done in a second step. I'll happily merge as it is today if you push to the right.

**Comment by brownzach125** [comment]
I fixed the divide. I decided to just match the width of the queue view. It simplifies things and leaves room for the progress bar later.

**Comment by fabiofalci** [comment]
@brownzach125 I tested quickly on macOS and sconsify is freezing after some seconds playing a track. Not sure if related to this feature. Just wanted to know if you by any chance have noticed this? Not sure if you use a mac or linux though.

I'll try to test more this later.

**Comment by brownzach125** [comment]
@fabiofalci I use a linux primarily but I also have a mac so I'll try to find this is as well. I didn't notice any issues on linux.

**Comment by brownzach125** [comment]
@fabiofalci I tried reproducing the issue on my mac book pro 14 with os el capitan. I'm not experiencing any issues :(

**Comment by fabiofalci** [comment]
Ok. I'm testing on sierra.
Will try to test more later.

Thanks.

**Pull request merged**
